version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          commmand: |
            python -m pip install --upgrade pip
            source .venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            export TEST=True
            pytest -v
